services:
  postgres:
    image: postgres:15-alpine
    container_name: slack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: slack
      POSTGRES_USER: slack_user
      POSTGRES_PASSWORD: slack_password
    networks:
      - slack_network
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: slack_redis
    restart: unless-stopped
    networks:
      - slack_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    container_name: slack_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: slack_user
      MONGO_INITDB_ROOT_PASSWORD: slack_password
    restart: unless-stopped
    networks:
      - slack_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: slack_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: slack_user
      RABBITMQ_DEFAULT_PASS: slack_password
    networks:
      - slack_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth-service:
    build: ./services/auth
    container_name: slack-auth-service
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./services/auth/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/auth/package.json
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://slack_user:slack_password@postgres:5432/slack
      - JWT_SECRET=your-secret-key
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - slack_network
    # volumes:
    #   - ./services/auth:/app
    #   - /app/node_modules
    command: npm run dev

networks:
  slack_network:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  rabbitmq_data:
